name: Deploy to CentOS Server

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t my-dotnet-service:${{ github.sha }} .
          docker save -o my-dotnet-service.tar.gz my-dotnet-service:${{ github.sha }}

      - name: Copy Docker image to server and run
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CENTOS_SERVER }}
          username: ${{ secrets.CENTOS_USERNAME }}
          password: ${{ secrets.CENTOS_PASSWORD }}
          source: my-dotnet-service.tar.gz
          target: /home/phejmej

      #- name: RUN
      #  run: |
      #    ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} -t ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} bash /tmp/deploy.sh

      - name: Deploy to CentOS server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CENTOS_SERVER }}
          username: ${{ secrets.CENTOS_USERNAME }}
          password: ${{ secrets.CENTOS_PASSWORD }}
          script: |
            touch test.txt
            docker stop my-dotnet-service || true
            docker rm my-dotnet-service || true
            docker run -d --name my-dotnet-service -p 8080:80 -e DISCORD_KEY=${{ secrets.DISCORD_TOKEN }} my-dotnet-service:${{ github.sha }}
